FROM scratch 

MAINTAINER João Antonio Ferreira "joao.parana@gmail.com"

# Baseado no post https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

ADD /linux-solutions-debian-64 / 
CMD ["/linux-solutions-debian-64"]
