FROM scratch 

MAINTAINER João Antonio Ferreira "joao.parana@gmail.com"

# Baseado no post https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

ENV blog_addr   http://64.111.112.150

ADD linux-solutions-debian-64 / 
CMD ["/linux-solutions-debian-64"]
